"""Second pass: resolve remaining images via Wikipedia search + aliases, merge into image_urls.py."""

import json
import re
import time
import httpx
from app.db.seed_data import CITIES, PLACES
from app.db.image_urls import CITY_IMAGES, PLACE_IMAGES

API = "https://en.wikipedia.org/w/api.php"
client = httpx.Client(
    timeout=15,
    headers={"User-Agent": "GoWanderStudentProject/1.0 (contact: axel@example.com)"},
)

ALIASES = {
    "New York": "New York City",
    "Chatuchak Market": "Chatuchak Weekend Market",
    "Sacré-Cœur Basilica": "Sacré-Cœur, Paris",
    "Marina Bay Sands SkyPark": "Marina Bay Sands",
    "Senso-ji Temple": "Sensō-ji",
    "Tsukiji Outer Market": "Tsukiji fish market",
    "teamLab Planets": "TeamLab (art collective)",
    "Kaleiçi Old Town": "Kaleiçi",
    "Changdeokgung Secret Garden": "Changdeokgung",
    "Kuromon Market": "Kuromon Ichiba Market",
    "Mina Valley": "Mina, Saudi Arabia",
    "Big Buddha": "Great Buddha of Phuket",
    "Karon Viewpoint": "Karon, Phuket",
    "Nong Nooch Garden": "Nong Nooch Tropical Botanical Garden",
    "Koh Larn": "Ko Lan",
    "Big Buddha Hill": "Wat Phra Yai Pattaya",
    "Navigli District": "Navigli",
    "Barceloneta Beach": "La Barceloneta, Barcelona",
    "Tian Tan Big Buddha": "Tian Tan Buddha",
    "La Seu Cathedral": "Palma Cathedral",
    "Old Town Palma": "Palma de Mallorca",
    "Playa de Palma": "Platja de Palma",
    "Tegallalang Rice Terraces": "Tegallalang",
    "Sacred Monkey Forest": "Ubud Monkey Forest",
    "Seminyak Beach": "Seminyak",
    "Vatican Museums & Sistine Chapel": "Vatican Museums",
    "Canal Cruise": "Canals of Amsterdam",
    "Mercado San Miguel": "Mercado de San Miguel",
    "Reichstag Dome": "Reichstag dome",
    "Memorial to the Murdered Jews": "Memorial to the Murdered Jews of Europe",
    "Chichén Itzá Day Trip": "Chichen Itza",
    "Playa Delfines": "Cancún",
    "Cenote Dos Ojos": "Dos Ojos",
    "High Roller Wheel": "High Roller (Ferris wheel)",
    "Red Rock Canyon": "Red Rock Canyon National Conservation Area",
    "Wynwood Walls": "Wynwood",
    "Alfama & Tram 28": "Alfama",
    "Grand Canal & Rialto": "Rialto Bridge",
    "Murano & Burano": "Burano",
    "Gondola Ride": "Gondola",
    "Duomo & Brunelleschi's Dome": "Florence Cathedral",
    "Piazzale Michelangelo": "Piazzale Michelangelo",
    "Acropolis & Parthenon": "Acropolis of Athens",
    "Plaka District": "Plaka",
    "Széchenyi Thermal Baths": "Széchenyi Thermal Bath",
    "Ruin Bars (Szimpla Kert)": "Szimpla Kert",
    "Trinity College & Book of Kells": "Trinity College Dublin",
    "Selarón Steps": "Escadaria Selarón",
    "La Boca & Caminito": "Caminito",
    "San Telmo Market": "San Telmo, Buenos Aires",
    "Pyramids of Giza & Sphinx": "Great Pyramid of Giza",
    "Nile Felucca Ride": "Felucca",
    "The Souks": "Marrakesh",
    "Kirstenbosch Gardens": "Kirstenbosch National Botanical Garden",
    "CN Tower": "CN Tower",
    "Musée d'Orsay": "Musée d'Orsay",
    "Gold Souk": "Dubai Gold Souk",
    "Makkah Mall": "Mecca",
    "Old Phuket Town": "Phuket City",
}


def search_image(query: str) -> str | None:
    for attempt in range(4):
        try:
            r = client.get(API, params={
                "action": "query", "generator": "search", "gsrsearch": query, "gsrlimit": 1,
                "prop": "pageimages", "pithumbsize": 800, "format": "json", "maxlag": 5,
            })
            if r.status_code != 200:
                time.sleep(2 * (attempt + 1))
                continue
            pages = r.json().get("query", {}).get("pages", {})
            for page in pages.values():
                thumb = page.get("thumbnail", {}).get("source")
                if thumb:
                    return thumb
            return None
        except Exception:
            time.sleep(2)
    return None


def main():
    city_images = dict(CITY_IMAGES)
    place_images = dict(PLACE_IMAGES)

    for _, city, country, *_ in CITIES:
        if city in city_images:
            continue
        url = search_image(ALIASES.get(city, f"{city} {country}"))
        if url:
            city_images[city] = url
        print(f"city {city}: {'ok' if url else 'STILL MISSING'}")
        time.sleep(0.4)

    for city, places in PLACES.items():
        for p in places:
            key = f"{city}|{p[0]}"
            if key in place_images:
                continue
            query = ALIASES.get(p[0], re.sub(r"[&(].*", "", p[0]).strip() + f" {city}")
            url = search_image(query)
            if url:
                place_images[key] = url
            print(f"  {key}: {'ok' if url else 'STILL MISSING'}")
            time.sleep(0.4)

    out = (
        '"""Real Wikipedia image URLs for seed data. Generated by scripts/fetch_images*.py."""\n\n'
        f"CITY_IMAGES = {json.dumps(city_images, indent=2, ensure_ascii=False)}\n\n"
        f"PLACE_IMAGES = {json.dumps(place_images, indent=2, ensure_ascii=False)}\n"
    )
    with open("app/db/image_urls.py", "w") as f:
        f.write(out)
    total = sum(len(v) for v in PLACES.values())
    print(f"\nNow have {len(city_images)}/50 cities, {len(place_images)}/{total} places")


if __name__ == "__main__":
    main()
