"""
One-off: resolve a real Wikipedia image URL for every city and place in the
seed catalogue. Writes app/db/image_urls.py with the results.
Run: PYTHONPATH=. .venv/bin/python scripts/fetch_images.py
"""

import json
import time
import urllib.parse
import httpx
from app.db.seed_data import CITIES, PLACES

REST = "https://en.wikipedia.org/api/rest_v1/page/summary/"
client = httpx.Client(
    timeout=15,
    follow_redirects=True,
    headers={"User-Agent": "GoWanderStudentProject/1.0 (contact: axel@example.com)"},
)


def summary_image(title: str) -> str | None:
    """Lead image for an exact-ish Wikipedia title (REST API resolves redirects)."""
    for attempt in range(3):
        try:
            r = client.get(REST + urllib.parse.quote(title, safe=""))
            if r.status_code == 429:
                time.sleep(2 * (attempt + 1))
                continue
            if r.status_code != 200:
                return None
            data = r.json()
            img = data.get("thumbnail", {}).get("source") or data.get("originalimage", {}).get("source")
            return img
        except Exception:
            time.sleep(1)
    return None


def resolve(*candidates: str) -> str | None:
    for c in candidates:
        url = summary_image(c)
        if url:
            return url
        time.sleep(0.15)
    return None


def main():
    city_images: dict[str, str] = {}
    place_images: dict[str, str] = {}

    for name, city, country, *_ in CITIES:
        url = resolve(city, f"{city}, {country}", name)
        if url:
            city_images[city] = url
        print(f"city {city}: {'ok' if url else 'MISS'}")
        time.sleep(0.15)

    for city, places in PLACES.items():
        for p in places:
            p_name = p[0]
            url = resolve(p_name, f"{p_name} ({city})", f"{p_name}, {city}")
            if url:
                place_images[f"{city}|{p_name}"] = url
            print(f"  {city} / {p_name}: {'ok' if url else 'MISS'}")
            time.sleep(0.15)

    out = (
        '"""Real Wikipedia image URLs for seed data. Generated by scripts/fetch_images.py."""\n\n'
        f"CITY_IMAGES = {json.dumps(city_images, indent=2, ensure_ascii=False)}\n\n"
        f"PLACE_IMAGES = {json.dumps(place_images, indent=2, ensure_ascii=False)}\n"
    )
    with open("app/db/image_urls.py", "w") as f:
        f.write(out)
    print(f"\nWrote {len(city_images)} city + {len(place_images)} place images")


if __name__ == "__main__":
    main()
